# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/Lucas-C/pre-commit-hooks-java
    rev: 1.3.10
    hooks:
    -   id: validate-html
-   repo: https://github.com/Lucas-C/pre-commit-hooks-lxml
    rev: v1.1.0
    hooks:
    -   id: forbid-html-img-without-alt-text
    -   id: forbid-non-std-html-attributes
    -   id: detect-missing-css-classes
        args:
        - --css-files-dir
        - .
        - --html-files-dir
        - .
    -   id: html-tags-blacklist
    -   id: html-attributes-blacklist
